# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.routing_loader:
        class: AppBundle\Routing\DbLoader
        tags:
            - { name: routing.loader }
        arguments:
            - '@doctrine.orm.default_entity_manager'
